sudo: false
language: java
jdk:
  - openjdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
  - "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
  - "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP_PLUGIN_VERSION}"
  - "export ORG_GRADLE_PROJECT_annotationPluginVersion=${ANNOTATION_PLUGIN_VERSION}"

env:
  - IDEA_VERSION="IU-2019.1.2" PHP_PLUGIN_VERSION="191.7141.52" ANNOTATION_PLUGIN_VERSION="5.3"


script:
- "./gradlew check verifyPlugin buildPlugin"
